api/urls.py
from django.urls import path, include
from .views import BookListApiView, AuthorListApiView, BookViewSets
from .views import (BookApiNew, BookApiUpdateView, AuthorViewSetApi, book, book_detail,
                    BookApiView,snippet_detail, BookDetailView, UserViewSet, author, LoginView, LogoutView)
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'books', BookViewSets)
router.register('author_api', AuthorViewSetApi)
router.register('users', UserViewSet)

urlpatterns = [
    path('book/', BookListApiView.as_view()),
    path('book/<int:id>/', BookListApiView.as_view()),
    # path('books_func/', book),
    path('books_func/<int:id>/', BookDetailView.as_view()),
    path('books_func/', BookApiView.as_view()),
    path('books_func/<int:id>/', book_detail),
    # path('author/', AuthorListApiView.as_view()),
    # path('author/', author),
    path('book/new/', BookApiNew.as_view()),
    path('book/<int:pk>/', BookApiUpdateView.as_view()),
    path('snippet/<int:pk>/', snippet_detail),
    # path('rest-auth/', include('rest_auth.urls')),
    path('auth/login/', LoginView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path(r'rest-auth/registration/', include('rest_auth.registration.urls')),
    # path('book/view/', BookViewSets.as_view()),

    path('', include(router.urls)),
]

catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    #Index
    path('', views.index, name='index'),
    #Books
    path('books/', views.BookListView.as_view(), name='book'),
    path('books/create/', views.BookCreateView.as_view(), name='book-create'),
    path('books/<int:pk>', views.BookDetialView.as_view(), name='book-detail'),
    path('books/<int:pk>/edit/', views.BookUpdateView.as_view(), name='book-edit'),
    path('books/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('allbooks/', views.LoanedBooksByAdminListview.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    #Author
    path('authors/', views.AuthorListView.as_view(), name='author'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('authors/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    # path('book/<uuid:pk>/renew-model-form/', views.RegisterView, name='renew-modelform-book-librarian'),
    
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
# urlpatterns += [
#     path('catalog/', include('catalog.urls')),
#     path('', RedirectView.as_view(url='/catalog/', permanent=True)),
# ]
urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('api/v1/', include('api.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('catalog/', include('catalog.urls')),
    path('rest/', include('rest.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% block title %}
      <title>Local Library</title>
  {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:index' %}">Home</a></li>
          <li><a href="{% url 'catalog:book' %}">All books</a></li>
          <li><a href="{% url 'catalog:author' %}">All authors</a></li>
        {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            <li><a href="{% url 'catalog:my-borrowed' %}">My Borrowed </a> </li>
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
        {% endif %}
        {% if user.is_superuser %}
        <li><a href="{% url 'catalog:all-borrowed' %}">All Borrowed </a> </li>
        {% endif %}
        </ul>
      {% endblock %}

      </div>
      <div class="col-sm-10 ">
          {% block content %}{% endblock %}

            {# pagination block     #}
          {% block pagination %}
              {% if is_paginated %}
                <div class="pagination">
                  <span class="page-links">
                    {% if page_obj.has_previous %}
                      <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                      <p>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
                    </span>
                    {% if page_obj.has_next %}
                      <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                  </span>
                </div>
              {% endif %}
          {% endblock %}
      </div>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% block js_block %}
    {% endblock %}
    </div>
  </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}<title> Locallibrary Index</title> {% endblock %}
{% block content %}
    <h1>Local Library Home</h1>
    <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong>{{ num_books }}</li>
        <li><strong>Copies:</strong>{{ num_instance }}</li>
        <li><strong>Copies available:</strong>{{ num_instance_available }}</li>
        <li><strong>Authors:</strong>{{ num_author }}</li>
        <li><strong>Genre:</strong>{{ num_genre }}</li>
        <li><strong>Number of books contain b:</strong>{{ num_of_insensetive_books }}</li>
        <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
    </ul>
{% endblock %}