api/urls.py
from django.urls import path, include
from .views import BookListApiView, AuthorListApiView, BookViewSets
from .views import (BookApiNew, BookApiUpdateView, AuthorViewSetApi, book, book_detail,
                    BookApiView,snippet_detail, BookDetailView, UserViewSet, author, LoginView, LogoutView)
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'books', BookViewSets)
router.register('author_api', AuthorViewSetApi)
router.register('users', UserViewSet)

urlpatterns = [
    path('book/', BookListApiView.as_view()),
    path('book/<int:id>/', BookListApiView.as_view()),
    # path('books_func/', book),
    path('books_func/<int:id>/', BookDetailView.as_view()),
    path('books_func/', BookApiView.as_view()),
    path('books_func/<int:id>/', book_detail),
    # path('author/', AuthorListApiView.as_view()),
    # path('author/', author),
    path('book/new/', BookApiNew.as_view()),
    path('book/<int:pk>/', BookApiUpdateView.as_view()),
    path('snippet/<int:pk>/', snippet_detail),
    # path('rest-auth/', include('rest_auth.urls')),
    path('auth/login/', LoginView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path(r'rest-auth/registration/', include('rest_auth.registration.urls')),
    # path('book/view/', BookViewSets.as_view()),

    path('', include(router.urls)),
]

catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    #Index
    path('', views.index, name='index'),
    #Books
    path('books/', views.BookListView.as_view(), name='book'),
    path('books/create/', views.BookCreateView.as_view(), name='book-create'),
    path('books/<int:pk>', views.BookDetialView.as_view(), name='book-detail'),
    path('books/<int:pk>/edit/', views.BookUpdateView.as_view(), name='book-edit'),
    path('books/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('allbooks/', views.LoanedBooksByAdminListview.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    #Author
    path('authors/', views.AuthorListView.as_view(), name='author'),
    path('authors/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('authors/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),
    # path('book/<uuid:pk>/renew-model-form/', views.RegisterView, name='renew-modelform-book-librarian'),
    
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
# urlpatterns += [
#     path('catalog/', include('catalog.urls')),
#     path('', RedirectView.as_view(url='/catalog/', permanent=True)),
# ]
urlpatterns = [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('admin/', admin.site.urls),
    #path('api/', include('api.urls')),
    path('api/v1/', include('api.urls')),
    path('api/v1/auth/', include('rest_framework.urls')),
    path('catalog/', include('catalog.urls')),
    path('rest/', include('rest.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date
import  uuid
# Create your models here.


class Genre(models.Model):
    """Model representing a book genre"""

    name = models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=120, blank=True, null= True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class Book(models.Model):
    """ Model representing books """
    title   = models.CharField(max_length=120)
    author  = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField()
    isbn    = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre   = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    price   = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    edited_by  = models.ForeignKey(User, default=None, blank=True, null=True, on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, blank=True, null=True, on_delete=models.CASCADE, related_name="creator")
    edit_by = models.ForeignKey(User, default=None, null=True, blank=True, on_delete=models.CASCADE, related_name='editor')


    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('catalog:book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book    = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=120)
    due_back = models.DateField(null=True, blank = True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m','Maintenace'),
        ('o','On loan'),
        ('a','Available'),
        ('r','Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned","Set a book as returned"),)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f'{self.id}({self.book.title})' # '{0} ({1})'.format(self.id,self.book.title)).


class Author(models.Model):
    """Model representing an author."""
    first_name  = models.CharField(max_length=120)
    last_name   = models.CharField(max_length=120)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name} {self.last_name}'


class Snippet(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, default='')
    code = models.TextField()

    def __str__(self):
        return self.title

catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin.widgets import AdminDateWidget

from catalog.models import BookInstance

class RenueBooksForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter the date between 4 weeks (default 3). ", widget=forms.TextInput(attrs=
                                {
                                    'id':'datepicker'
                                }))

    # check if the date is in past
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

    class Meta:
        model   = BookInstance
        fields  = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
import datetime

from django.contrib.auth.decorators import (permission_required,
                                            user_passes_test)
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import edit as editViews

from catalog.models import Author, Book, BookInstance, Genre

from .forms import RenewBookModelForm, RenueBooksForm

# Create your views here.


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instance = BookInstance.objects.all().count()

    num_instance_available = BookInstance.objects.filter(status__iexact='a').count() # Available books (status = 'a')
    num_author = Author.objects.all().count()  # number of author
    num_genre = Genre.objects.all().count()     # number of genre
    num_of_insensetive_books = Book.objects.filter(title__icontains='b')  # num of books in case insensitive
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books' : num_books,
        'num_instance' : num_instance,
        'num_instance_available': num_instance_available,
        'num_author' : num_author,
        'num_genre'  : num_genre,
        'num_of_insensetive_books' : num_of_insensetive_books,
        'num_visits' : num_visits,
    }

    return render(request, 'index.html', context)

class BookListView(generic.ListView):
    model = Book
    queryset = Book.objects.filter(title__icontains='book')[:5]
    template_name = 'catalog/book_list.html'
    paginate_by = 4

class BookDetialView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    queryset = Author.objects.all()

class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    Model = BookInstance
    template_name = 'catalog/bookinstance_borrowed_list_user_view.html'
    paginate_by = 2

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class MyPermissionView(PermissionRequiredMixin):
    permission_required = 'catalog.can_mark_returned'

@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class LoanedBooksByAdminListview(generic.ListView):
    """ Generic class-based view listing books on loan to current user """
    Model = BookInstance
    template_name   = 'catalog/bookinstance_borrowed_list_user_view.html'
    # paginate_by     = 4

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


# def renew_book_librarian(request, pk):
#     book_instance = get_list_or_404(BookInstance, pk=pk)
#
#     # If this is a POST request then process the Form data
#     if request.method == 'POST':
#         form = RenueBooksForm(request.POST)
#
#         if form.is_valid():
#             book_instance.due_back = form.cleaned_data['renewal_date']
#             book_instance.save()
#
#             return HttpResponseRedirect(reverse('catalog:all-borrowed'))
#
#     else:
#         proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
#         form = RenueBooksForm(initial={'renewal_date' : proposed_renewal_date })
#
#
#     context = {
#         'form' : form,
#         'book_instance' : book_instance
#     }
#
#     return render(request, 'catalog/book_renew_librarian.html', context)

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenueBooksForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('catalog:all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenueBooksForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form' : form,
        'book_instance' : book_instance
    }
    return render(request, 'catalog/book_renew_librarian.html', context)


# class RegisterView(editViews.FormView):
#
#     form_class = RenewBookModelForm
#     template_name= 'catalog/book_renew_librarian.html'
#
#     def get_context_data(self, pk, **kwargs):
#         context = super(RegisterView, self).get_context_data(**kwargs)
#         import pdb;pdb.set_trace()
#         context['book_instance'] = BookInstance.objects.filter(id=pk)
#         return context
#
#     def form_valid(self, form):
#         request = self.request
#         form.save()
#         return render(self.request, 'register/thank_you.html')


class AuthorCreateView(editViews.CreateView):
    model = Author
    fields = '__all__'
    initial = { 'date_of_death' : '05/01/2018' }

class AuthorUpdateView(editViews.UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', ]

class AuthorDeleteView(editViews.DeleteView):
    model = Author
    success_url = reverse_lazy('catalog:author')


class BookCreateView(editViews.CreateView):
    model = Book
    fields = ['title','author','summary','isbn','genre']
    template_name = 'catalog/book_create.html'

class BookUpdateView(editViews.UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/book_create.html'

class BookDeleteView(editViews.DeleteView):
    model = Book
    success_url = reverse_lazy('catalog:book')

catalog/templates/catalog/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Author</h1>
    <p>Are you sure want to delete author {{ author }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, Delete">
    </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Name: {{ author.first_name }} {{author.last_name}}</h1>
    <p><strong>Date Of Birth:</strong>{{ author.date_of_birth }}
    {% if author.date_of_death %}
        <p><strong>Date of death:</strong>{{ author.date_of_death }}
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {%csrf_token%}
        <table>
            <tr>
                <td>{{ form.first_name.label_tag }}</td>
                <td>{{ form.first_name }}</td>
            </tr>
            <tr>
                <td>{{ form.last_name.label_tag }}</td>
                <td>{{ form.last_name }}</td>
            </tr>
            <tr>
                <td>{{ form.date_of_birth.label_tag }}</td>
{#                <td>{{ form.date_of_birth }}</td>#}
                <td>
                    <input type="text" name="date_of_birth" value="{{form.date_of_birth.value|date:'Y-m-d'}}" id="id_date_of_birth">
                </td>
            </tr>
            <tr>
                <td>{{ form.date_of_death.label_tag }}</td>
{#                <td>{{ form.date_of_death }}</td>#}
                <td>
                    <input type="type" name="date_of_death"  id="id_date_of_death" value="{{ form.date_of_death.value|date:'Y-m-d' }}">
                </td>

            </tr>
        </table>
        <input type="submit" value="submit">
    </form>
{% endblock %}
{% block js_block %}
    <script>
      $( function() {
        $( "#id_date_of_death" ).datepicker({
            dateFormat: "yy-mm-dd"
        });
      } );
      $( function() {
        $( "#id_date_of_birth" ).datepicker({
            dateFormat: "yy-mm-dd"
        });
      } );
  </script>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base.html' %}
{% block title %}<title>Author List</title>{% endblock %}

{% block content %}
    <h1>Author List</h1>
    <a href="{%url 'catalog:author-create'%}">Add new</a>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
{#                <li><a href="{% url 'catalog:book-detail' pk=book.id %}">{{ book.title }}</a> {{ book.author }}</li>#}
                <!-- <li><a href="{%url 'catalog:author-detail' pk=author.id %}">{{ author.first_name }} {{author.last_name}}</a></li> -->
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name}}</a>
                    <a class="text-warning" href="{%url 'catalog:author-update' pk=author.id %}">edit</a>
                    <a class="text-danger" href="{%url 'catalog:author-delete' pk=author.id %}">delete</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>no author found</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete book</h1>
    <p>Are you sure want to delete book {{ book }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, Delete">
    </form>
{% endblock %}

catalog/templates/catalog/book_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {%csrf_token%}
        <table>
            <tr>
                <td>{{ form.title.label_tag }}</td>
                <td>{{ form.title }}</td>
            </tr>
            <tr>
                <td>{{ form.author.label_tag }}</td>
                <td>{{ form.author }}</td>
            </tr>
            <tr>
                <td>{{ form.summery.label_tag }}</td>
                <td>{{ form.summary }}</td>
{#                <td>#}
{#                    <input type="text" name="date_of_birth" value="{{form.date_of_birth.value|date:'Y-m-d'}}" id="id_date_of_birth">#}
{#                </td>#}
            </tr>
            <tr>
                <td>{{ form.isbn.label_tag }}</td>
                <td>{{ form.isbn }}</td>
{#                <td>#}
{#                    <input type="type" name="date_of_death"  id="id_date_of_death" value="{{ form.date_of_death.value|date:'Y-m-d' }}">#}
{#                </td>#}

            </tr>
            <tr>
                <td>{{ form.genre.label_tag }}</td>
                <td>{{ form.genre }}</td>
            </tr>
        </table>
        <input type="submit" value="submit">
    </form>
{% endblock %}
{% block js_block %}
    <script>
      $( function() {
        $( "#id_date_of_death" ).datepicker({
            dateFormat: "yy-mm-dd"
        });
      } );
      $( function() {
        $( "#id_date_of_birth" ).datepicker({
            dateFormat: "yy-mm-dd"
        });
      } );
  </script>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong> <a href="{% url 'catalog:author-detail' pk=book.author.id %}">{{ book.author }}</a>
    <p><strong>Summary:</strong>{{ book.summary }}
    <p><strong>ISBN:</strong>{{ book.isbn }}
    <p><strong>Genre:</strong>{% for genre in book.genre.all %}{{ genre }}{% if not forloop.last %},{% endif %}{% endfor %}

    <div style="margin-left: 20px; margin-top: 20px">
        <h1>copies</h1>
        {% for copy in book.bookinstance_set.all %}
            <p class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %} text-danger {% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>

            {% if copy.status != 'a' %}
                <p><strong>Due to be returned: {{ copy.due_back }}</strong></p>
            {% endif %}
            <p>Imprint: {{ copy.imprint }}</p>
            <p class="text-muted"><strong>ID:</strong>{{ copy.id }}</p>
        {% endfor %}
    </div>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base.html' %}
{% block title %}<title>Book List</title>{% endblock %}

{% block content %}
    <h1>Book List</h1>
    <a href="{% url 'catalog:book-create' %}">Create New</a>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
{#                <li><a href="{% url 'catalog:book-detail' pk=book.id %}">{{ book.title }}</a> {{ book.author }}</li>#}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {{ book.author }}
                    <a class="text-warning" href="{% url 'catalog:book-edit' pk=book.id %}">edit</a>
                    <a class="text-danger" href="{% url 'catalog:book-delete' pk=book.id %}">delete</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>no books found</p>
    {% endif %}

    <h>Book List as object_list</h>
    {% if object_list %}
        <ul>
        {% for book in object_list %}
            <li>
{#                <a href="{% url 'catalog:book-detail' pk=book.id %}">{{ book.title }}</a> {{ book.author }}#}
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {{ book.author }}
            </li>
        {% endfor %}
        </ul>
    {% else %}
    <p>no books found</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends 'base.html' %}

{% block content %}
    <p>Book title: {{ book_instance.book.title }}</p>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p class="{% if book_instance.is_overdue %} text-danger {% endif %}">Due Back: {{ book_instance.due_back }}</p>

    {% if form.errors %}
        <p>please enter a valid form data</p>
    {% endif %}
    <form action="" method="POST">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.renewal_date.label_tag }}</td>
        <td>{{ form.renewal_date }}</td>
    </tr>
{#        {{ form.as_table }}#}
    </table>
        <input type="submit" value="submit">
    </form>
{% endblock %}
{% block js_block %}
    <script>
      $( function() {
        $( "#datepicker" ).datepicker({
            dateFormat: "yy-mm-dd"
        });
      } );
  </script>
{% endblock %}

catalog/templates/catalog/bookinstance_borrowed_list_user_view.html
{% extends 'base.html' %}

{% block title %}<title>Book List</title>{% endblock %}


{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                {{ bookinst.id }}
                <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
                    <a href="{% url 'catalog:book-detail' bookinst.book.id %}">{{ bookinst.book.title }}</a>({{ bookinst.due_back }}){% if user.is_superuser %}({{bookinst.borrower}}){% if perms.catalog.can_mark_returned %}- <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
{% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no books borrowed</p>
    {% endif %}


{% endblock %}